### PR TITLE
support for persisting models via utilizing cached versions of resources

### PR DESCRIPTION
**Pull request by repodiac**
Hi, this is a PR according to my post and correspondence with user "gez-mycroft" on the forum:

https://community.mycroft.ai/t/padatious-intent-parser-how-can-i-save-store-persist-trained-models-to-disk/6899

### CODE REVIEW

**Comment by MatthewScholefield** [comment]
Hi, sorry for the delay on this. I'd be happy to pull this in once those PEP8 problems listed above are fixed. You can probably run [autopep8](https://github.com/hhatto/autopep8) to fix most of them.

This looks like a good approach. This does change the meaning of `intent_cache` to more of a `models_folder` (so we might want to rename some variables in the future), but implementation wise this looks good.

Another thing I would consider is making this more of an official thing my storing some `model_name.json` or something that is a json referencing all the mini model files rather than interpreting them from the file names listed in the folder. However, this is something me or you could add in the future.

**Comment by MatthewScholefield** [comment]
@repodiac Ping (see above)

**Comment by repodiac** [comment]
Hi @MatthewScholefield  - sorry, I did not get notified about the new posts here or in the MyCroft forum! I am really happy to hear that you accept the PR (my very first :-) Of course, I can do the PEP8 adaptions... will do now and push the updates.

**Comment by repodiac** [comment]
I hope this is sufficient? (see commit #0404736)

**Comment by krisgesling** [comment]
Hey @repodiac thanks again for this. I'll let Matthew review the changes, but wanted to make sure we had a CLA ready to go.

To protect yourself, the project, and users of Mycroft technologies we require a Contributor Licensing Agreement (CLA) before accepting any code contribution. This agreement makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.

You will also be added to [our list of excellent human beings](https://github.com/MycroftAI/contributors)!

Please visit https://mycroft.ai/cla to initiate this one-time signing.

Thank you!

**Comment by repodiac** [comment]
Hi, I now tried 3 times to get das CLA to be able to proceed... I also checked my spam folder or the like: I did not receive a link to the form as promised on the webpage for the CLA!? Can you please check back with the person in charge? I really would like to see this PR included :-) Thanx!

**Comment by krisgesling** [comment]
Hi @repodiac, if you haven't yet received the email from HelloSign, can you email me directly - kris dot gesling at mycroft dot ai
Once I know your email, I can then chase it up directly. 
Thanks

**Comment by repodiac** [comment]
Hi Kris, I just signed the CLA document (note: the given eMail address there is different from the one of my repo/my pull request/commits for privacy reasons)

Hope this whole thing can now fly :-)

**Comment by krisgesling** [comment]
CLA received, merging this now, thanks again!

**Pull request merged**
