### PR TITLE
PR for fixing issue #23

### PR DESCRIPTION
**Pull request by repodiac**
see https://github.com/MycroftAI/padatious/issues/23 for further details

### CODE REVIEW

**Comment by repodiac** [comment]
>     * In the file [`padatious/intent_container.py`](https://github.com/MycroftAI/padatious/blob/3c67790e21c716c15843f23ffefe0eb6f97ab64f/padatious/intent_container.py):
> 
> 
> > [Line 76:101](https://github.com/MycroftAI/padatious/blob/3c67790e21c716c15843f23ffefe0eb6f97ab64f/padatious/intent_container.py#L76): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (118 > 100 characters)
> 
>     * In the file [`padatious/training_manager.py`](https://github.com/MycroftAI/padatious/blob/3c67790e21c716c15843f23ffefe0eb6f97ab64f/padatious/training_manager.py):
> 
> 
> > [Line 51:17](https://github.com/MycroftAI/padatious/blob/3c67790e21c716c15843f23ffefe0eb6f97ab64f/padatious/training_manager.py#L51): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented (comment)
> > [Line 52:17](https://github.com/MycroftAI/padatious/blob/3c67790e21c716c15843f23ffefe0eb6f97ab64f/padatious/training_manager.py#L52): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented (comment)

I checked back with running `autopep8 --in-place --aggressive --aggressive <file.py>` on the two files above... nothing changed. Does the bot have an alternative representation of PEP8? Can someone help here?

**Comment by forslund** [comment]
Let me look at the pep-8 things.

I'm a bit perplexed over the conflicts in this PR... It's not like much has changed recently.

Can you try to rebase to resolve those?

**Comment by repodiac** [comment]
Ehm... can you guide me hjere a little what you exactly mean? I also haven't "rebased" anything so far (I have an idea what the git command means/does though), can you provide me with an example what I should try here? Thanks!

**Comment by forslund** [comment]
I'm not 100% sure how it's done when you're using the dev-branch for doing the changes but I think the following will do the trick
Guessing the .../MycroftAI/padatious.git repo is called *upstream*

Fetch the latest dev from the upstream repo:
`git fetch upstream`
rebase your work on top of the latest upstream
`git rebase upstream/dev`

if the rebase halts due to conflicts correct them add the files that were corrected `git add FILE` then continue the rebase
`git rebase --continue`

Push the rebased branch to your repo
`git push -f origin dev`

The line length is 100 for this repo, the indentation of the comments should probably be moved out one level (since they refer to the `else` if I'm reading this correctly)

**Comment by repodiac** [comment]
Hi, I manually changed the line length in intent_container. Can you merge now?

The guidelines you gave me did NOT WORK, how do I get the "upstream" von MycroftAI padatious and merge (?) it with my padatious repo? I pushed/rebased my own repo but that obviously did not help?

**Comment by forslund** [comment]
You can also use the Resolve conflicts button here in the PR to try to fix the issues using github's online tool.

If you want to add the upstream repo so you can sync against it:
`git remote --verbose` will show you which remotes you have. I would guess you only have origin.

To add a new remote:
`git remote add upstream https://github.com/mycroftai/padatious`

**Comment by repodiac** [comment]
Ok, I tried to use the online tool - still don't get what the issue actually was but anyway. Now github complains, it cannot rebase... of course, I do not have write access to MycroftAI/padatious - can you do it instead?

[remark: sorry for being such a PITA... I am not used to this/familiar with OS PRs :/ - thank you for your help and understanding]

**Comment by repodiac** [comment]
Ok, I guess I made it! Thank you so much for your help, it worked out exactly as you mentioned

**Comment by forslund** [comment]
I've read through this and it seems like it does what's intended (if I understand it correctly :) ). I'll clean up the history a bit and merge it. Many thanks for this contribution

**Comment by repodiac** [comment]
Great! Hope to see it in the master branch soon (still waiting for it :/

**Pull request merged**
